import { Urbanist } from 'next/font/google'
import Image from 'next/image'
import './globals.css'
import './layout.style.css'

const inter = Urbanist({ subsets: ['latin'] })

export const metadata = {
  title: 'Baker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div id="main-navbar" className="navbar sticky top-0 z-50">
        <div className={inter.className}>
          <nav className='flex flex-col items-center justify-between'>
            <ul>
              <li>
                <a href="/home">Produtos</a>
              </li>
              <li>
                <a href="/home">Sobre</a>
              </li>
              <Image
                src="/assets/white-logo.png"
                className='nav__logo'
                width={50}
                height={50}
                alt="Baker Logo"
              />
              <li>
                <a href="/home">Localização</a>
              </li>
              <li>
                <a href="/home">Contato</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <body className={inter.className}>
        {children}
        </body>
    </html>
  )
}
