import { Urbanist } from 'next/font/google'
import Image from 'next/image'
import Provider from './components/Provider'
import SessionApp from './components/session'
import SignOut from './components/signout'
import './globals.css'
import './layout.style.css'

const inter = Urbanist({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Baker',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Baker</title>
      </head>
      <Provider>
        <div id="main-navbar" className="navbar sticky top-0 z-50">
          <div className={inter.className}>
            <nav className='flex flex-col items-center justify-between'>
              <ul>
                <a href="/">
                  <Image
                    src="/assets/white-logo.png"
                    className='nav__logo'
                    width={50}
                    height={50}
                    alt="Baker Logo"
                    href="/"
                  />
                </a>
                <li>
                  <a href="/produtos">Produtos</a>
                </li>
                <li>
                  <a href="/contato">Contato</a>
                </li>
                <li>
                  <a href="/carrinho">Carrinho</a>
                </li>
                <li>
                  <SessionApp/>
                </li>
                <li>
                  <SignOut/>
                </li>
                <li>
                  <a href="/cadastrar">Cadastrar</a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <body className={inter.className}>
          {children}
        </body>
      </Provider>
    </html>
  )
}
