'use client'
import { Urbanist } from 'next/font/google'
import Image from 'next/image'
import { handleSignOut } from './lib/users';
import './globals.css'
import './layout.style.css'
import Head from 'next/head';

const inter = Urbanist({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Baker',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  let user;

  const sair = () => {
    handleSignOut();
  }
  
  let li;
  if(user) {
    li = <li>
      <a href="/entrar">{user.name}</a>
    </li>
  } else {
    li = <li>
      <a href="/entrar">Entrar</a>
    </li>
  }

  return (
    <html lang="en">
      <head>
        <title>Baker</title>
      </head>
      <div id="main-navbar" className="navbar sticky top-0 z-50">
        <div className={inter.className}>
          <nav className='flex flex-col items-center justify-between'>
            <ul>
              <Image
                src="/assets/white-logo.png"
                className='nav__logo'
                width={50}
                height={50}
                alt="Baker Logo"
              />
              <li>
                <a href="/home">Produtos</a>
              </li>
              <li>
                <a href="/contato">Contato</a>
              </li>
              <li>
                <a onClick={sair}>Carrinho</a>
              </li>
              {li}
              <li>
                <a href="/cadastrar">Cadastrar</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <body className={inter.className}>
        {children}
        </body>
    </html>
  )
}
