'use client'

import React, { useState  } from "react";
import ProductCard from "../public/components/card";
import Slider from 'react-slick';

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

var settings = {
  dots: true,
  infinite: true,
  lazyLoad: true,
  speed: 500,
  slidesToShow: 1,
  slidesToScroll: 1,
  autoplay: true,
  autoplaySpeed: 5000
};

export default function Home() {
  const info = [
    {
      imgSrc: "/assets/white-logo.png",
      title: "Baker",
      description: "Generated by create next app cafe texto e mto texto",
    },
    {
      imgSrc: "/assets/brown-logo.png",
      title: "Baker",
      description: "Generated next app cafe texto e mto texto",
    }
  ];

  const [index, setIndex] = useState(0);

  const handleSelect = (selectedIndex) => {
    setIndex(selectedIndex);
  };

  return (
    <main className="pt-20">
      <div className="main__banner">
      </div>
      <div className="pt-10">
        <h1 className="text-[#d98b48] pb-4" style={{fontSize:"50px", paddingLeft:"23%"}}>Produtos</h1>
        <div className="carousel__section flex items-center justify-center">
          <div style={{width:'50%'}}>    
            <Slider {...settings}>
              <div>
                <ProductCard props={info[0]}/>
              </div>
              <div>
                <ProductCard props={info[1]}/>
              </div>
            </Slider>
          </div>
        </div>
      </div>
    </main>
  )
}
